name: My First Pipeline

on:
  push:

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4

      - name: Step 2 - Generate value
        id: gen
        run: echo "num=5" >> $GITHUB_OUTPUT

      - name: Step 3 - Use value
        run: echo "Value is ${{ steps.gen.outputs.num }}"

      - name: Step 4 - Only if value is 5
        if: steps.gen.outputs.num == '5'
        run: echo "Condition matched"
